import { MapItem } from './types';

export const urls = {
  firstMap: '/first',
  secondMap: '/second',
};

export const queryKeys = {
  getFirstMap: 'getFirstMap',
  getSecondMap: 'getSecondMap',
};

export const firstMap: MapItem[] = [
  {
    id: 'ceil-1',
    name: 'Сектор 1',
    available: 10,
    coordinates: [1, 1],
    number: 1,
  },
  {
    id: 'ceil-2',
    name: 'Сектор 2',
    available: 10,
    coordinates: [1, 1],
    number: 2,
  },
  {
    id: 'ceil-3',
    name: 'Сектор 3',
    available: 10,
    coordinates: [1, 1],
    number: 3,
  },
  {
    id: 'ceil-4',
    name: 'Сектор 4',
    available: 10,
    coordinates: [1, 1],
    number: 4,
  },
  {
    id: 'ceil-5',
    name: 'Сектор 5',
    available: 10,
    coordinates: [1, 1],
    number: 5,
  },
  {
    id: 'ceil-6',
    name: 'Сектор 6',
    available: 10,
    coordinates: [1, 1],
    number: 6,
  },
  {
    id: 'ceil-7',
    name: 'Сектор 7',
    available: 10,
    coordinates: [1, 1],
    number: 7,
  },
  {
    id: 'ceil-8',
    name: 'Сектор 8',
    available: 10,
    coordinates: [1, 1],
    number: 8,
  },
  {
    id: 'ceil-9',
    name: 'Сектор 9',
    available: 10,
    coordinates: [1, 1],
    number: 9,
  },
  {
    id: 'ceil-10',
    name: 'Сектор 10',
    available: 10,
    coordinates: [1, 1],
    number: 10,
  },
];

export const secondMap: MapItem[] = [
  {
    id: 'ceil-1',
    name: 'Сектор 1',
    available: 500,
    coordinates: [1, 1],
    number: 1,
  },
  {
    id: 'ceil-2',
    name: 'Сектор 2',
    available: 500,
    coordinates: [1, 1],
    number: 2,
  },
  {
    id: 'ceil-3',
    name: 'Сектор 3',
    available: 500,
    coordinates: [1, 1],
    number: 3,
  },
  {
    id: 'ceil-4',
    name: 'Сектор 4',
    available: 500,
    coordinates: [1, 1],
    number: 4,
  },
  {
    id: 'ceil-5',
    name: 'Сектор 5',
    available: 500,
    coordinates: [1, 1],
    number: 5,
  },
  {
    id: 'ceil-6',
    name: 'Сектор 6',
    available: 500,
    coordinates: [1, 1],
    number: 6,
  },
  {
    id: 'ceil-7',
    name: 'Сектор 7',
    available: 500,
    coordinates: [1, 1],
    number: 7,
  },
  {
    id: 'ceil-8',
    name: 'Сектор 8',
    available: 500,
    coordinates: [1, 1],
    number: 8,
  },
  {
    id: 'ceil-9',
    name: 'Сектор 9',
    available: 500,
    coordinates: [1, 1],
    number: 9,
  },
  {
    id: 'ceil-10',
    name: 'Сектор 10',
    available: 500,
    coordinates: [1, 1],
    number: 10,
  },
  {
    id: 'ceil-11',
    name: 'Сектор 11',
    available: 500,
    coordinates: [1, 1],
    number: 11,
  },
  {
    id: 'ceil-12',
    name: 'Сектор 12',
    available: 500,
    coordinates: [1, 1],
    number: 12,
  },
  {
    id: 'ceil-13',
    name: 'Сектор 13',
    available: 500,
    coordinates: [1, 1],
    number: 13,
  },
  {
    id: 'ceil-14',
    name: 'Сектор 14',
    available: 500,
    coordinates: [1, 1],
    number: 14,
  },
  {
    id: 'ceil-15',
    name: 'Сектор 15',
    available: 500,
    coordinates: [1, 1],
    number: 15,
  },
  {
    id: 'ceil-16',
    name: 'Сектор 16',
    available: 500,
    coordinates: [1, 1],
    number: 16,
  },
  {
    id: 'ceil-17',
    name: 'Сектор 17',
    available: 500,
    coordinates: [1, 1],
    number: 17,
  },
  {
    id: 'ceil-18',
    name: 'Сектор 18',
    available: 500,
    coordinates: [1, 1],
    number: 18,
  },
  {
    id: 'ceil-19',
    name: 'Сектор 19',
    available: 500,
    coordinates: [1, 1],
    number: 19,
  },
  {
    id: 'ceil-20',
    name: 'Сектор 20',
    available: 500,
    coordinates: [1, 1],
    number: 20,
  },
];
